name: programming_notebooks

dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - folium
  - bokeh
  - plotly
  - scikit-learn
  - pandas-datareader
  - ipywidgets
  - requests
  - xlrd
  - seaborn
  - sympy
  - scipy